

use db1
CREATE TABLE PRODUCT_MASTER(PRODUCTNO varchar(6) NOT NULL PRIMARY KEY, 
DESCRIPTION varchar(15) , 
PROFITPERCENT decimal(4,2) , 
UNIT_MEASURE varchar(10), 
QTYONHAND INTEGER , 
REORDERLVL INTEGER , 
SELLPRICE decimal(8,2),
COSTPRICE decimal(8,2));

select * from PRODUCT_MASTER
INSERT INTO PRODUCT_MASTER(PRODUCTNO , DESCRIPTION , PROFITPERCENT , UNIT_MEASURE, QTYONHAND , REORDERLVL , SELLPRICE ,COSTPRICE )VALUES('P00001','T-Shirt',5,'Piece',200,50,350,250);
INSERT INTO PRODUCT_MASTER(PRODUCTNO , DESCRIPTION , PROFITPERCENT , UNIT_MEASURE, QTYONHAND , REORDERLVL , SELLPRICE ,COSTPRICE )VALUES('P0345','Shirts',6,'Piece',150,50,500,350);
INSERT INTO PRODUCT_MASTER(PRODUCTNO , DESCRIPTION , PROFITPERCENT , UNIT_MEASURE, QTYONHAND , REORDERLVL , SELLPRICE ,COSTPRICE )VALUES('P06734','cotton jeans',5,'Piece',100,20,600,450) ;
INSERT INTO PRODUCT_MASTER(PRODUCTNO , DESCRIPTION , PROFITPERCENT , UNIT_MEASURE, QTYONHAND , REORDERLVL , SELLPRICE ,COSTPRICE )VALUES('P07865','jeans',5,'Piece',100,20,750,500);
INSERT INTO PRODUCT_MASTER(PRODUCTNO , DESCRIPTION , PROFITPERCENT , UNIT_MEASURE, QTYONHAND , REORDERLVL , SELLPRICE ,COSTPRICE )VALUES('P07868','trousers',2,'Piece',150,50,850,550);
INSERT INTO PRODUCT_MASTER(PRODUCTNO , DESCRIPTION , PROFITPERCENT , UNIT_MEASURE, QTYONHAND , REORDERLVL , SELLPRICE ,COSTPRICE )VALUES('P07885','pull overs',2.5,'Piece',80,30,700,450);
INSERT INTO PRODUCT_MASTER(PRODUCTNO , DESCRIPTION , PROFITPERCENT , UNIT_MEASURE, QTYONHAND , REORDERLVL , SELLPRICE ,COSTPRICE )VALUES('P07965','denim jeans',4,'Piece',100,40,350,250);
INSERT INTO PRODUCT_MASTER(PRODUCTNO , DESCRIPTION , PROFITPERCENT , UNIT_MEASURE, QTYONHAND , REORDERLVL , SELLPRICE ,COSTPRICE )VALUES('P07975','lycra tops',5,'Piece',70,30,300,175);
INSERT INTO PRODUCT_MASTER(PRODUCTNO , DESCRIPTION , PROFITPERCENT , UNIT_MEASURE, QTYONHAND , REORDERLVL , SELLPRICE ,COSTPRICE )VALUES('P08865','skirts',5,'Piece',75,30,450,300);

select * from PRODUCT_MASTER


SELECT DESCRIPTION FROM PRODUCT_MASTER;

 ALTER TABLE PRODUCT_MASTER MODIFY SELLPRICE DECIMAL(10,2);
 UPDATE PRODUCT_MASTER
SET COSTPRICE=950
WHERE DESCRIPTION='trousers';

DELETE FROM PRODUCT_MASTER WHERE QTYONHAND=100;
