use exp;
CREATE TABLE CLIENT_MASTER_1 (CLIENTNO varchar(6) check (CLIENTNO LIKE 'C%') Primary KEY,
NAME varchar(20) NOT NULL,
ADDRESS1 varchar(30),
ADDRESS2 varchar(30),
CITY varchar(15),
PINCODE integer,
STATE varchar(15),
BALDUE decimal(10,2));

select * from CLIENT_MASTER_1;

CREATE TABLE PRODUCT_MASTER_1(PRODUCTNO varchar(6) CHECK (PRODUCTNO LIKE 'P%') PRIMARY KEY, 
DESCRIPTION varchar(15) NOT NULL , 
PROFITPERCENT decimal(4,2) NOT NULL, 
UNIT_MEASURE varchar(10) NOT NULL , 
QTYONHAND INTEGER NOT NULL, 
REORDERLVL INTEGER NOT NULL, 
SELLPRICE decimal(8,2) NOT NULL,
COSTPRICE decimal(8,2) NOT NULL) ;

select * from PRODUCT_MASTER_1;

CREATE TABLE SALESMAN_MASTER_1( SALESMANNO VARCHAR(6) CHECK (SALESMANNO LIKE 'S%' )PRIMARY KEY ,
SALESMAN_NAME VARCHAR(20) NOT NULL,
ADDRESS1 VARCHAR(30) NOT NULL,
ADDRESS2 VARCHAR(30) ,
CITY VARCHAR(20) ,
PINCODE INTEGER ,
STATE VARCHAR(20) ,
SALAMT INTEGER NOT NULL,
TGTTOGET decimal(6,2) NOT NULL ,
YTDSALES decimal(6,2) NOT NULL ,
REMARKS VARCHAR(60));

SELECT * FROM SALESMAN_MASTER_1;

INSERT INTO CLIENT_MASTER_1(CLIENTNO , NAME , CITY , PINCODE , STATE , BALDUE)VALUES('C00001' , 'Ivan bayross' , 'Mumbai', 400054 , 'Maharashtra' , 15000);
INSERT INTO CLIENT_MASTER_1(CLIENTNO , NAME , CITY , PINCODE , STATE , BALDUE)VALUES('C00002' , 'Mamta muzumbar' , 'Madras', 780001 , 'Tamil nadu' , 0);
INSERT INTO CLIENT_MASTER_1(CLIENTNO , NAME , CITY , PINCODE , STATE , BALDUE)VALUES('C00003' , 'Chhaya bankar' , 'Mumbai', 400057 , 'Maharashtra' , 5000);
INSERT INTO CLIENT_MASTER_1(CLIENTNO , NAME , CITY , PINCODE , STATE , BALDUE)VALUES('C00004' , 'Ashwani joshi' , 'Bangalore', 560001 , 'Karnataka' , 0);
INSERT INTO CLIENT_MASTER_1(CLIENTNO , NAME , CITY , PINCODE , STATE , BALDUE)VALUES('C00005' , 'Hansel colaco' , 'Mumbai', 400060 , 'Maharashtra' , 2000);
INSERT INTO CLIENT_MASTER_1(CLIENTNO , NAME , CITY , PINCODE , STATE , BALDUE)VALUES('C00006' , 'Deepak sharma' , 'Mangalore', 560050 , 'Karnataka' , 0);

INSERT INTO PRODUCT_MASTER_1(PRODUCTNO , DESCRIPTION , PROFITPERCENT , UNIT_MEASURE, QTYONHAND , REORDERLVL , SELLPRICE ,COSTPRICE )VALUES('P00001','T-Shirt',5,'Piece',200,50,350,250);
INSERT INTO PRODUCT_MASTER_1(PRODUCTNO , DESCRIPTION , PROFITPERCENT , UNIT_MEASURE, QTYONHAND , REORDERLVL , SELLPRICE ,COSTPRICE )VALUES('P0345','Shirts',6,'Piece',150,50,500,350);
INSERT INTO PRODUCT_MASTER_1(PRODUCTNO , DESCRIPTION , PROFITPERCENT , UNIT_MEASURE, QTYONHAND , REORDERLVL , SELLPRICE ,COSTPRICE )VALUES('P06734','cotton jeans',5,'Piece',100,20,600,450) ;
INSERT INTO PRODUCT_MASTER_1(PRODUCTNO , DESCRIPTION , PROFITPERCENT , UNIT_MEASURE, QTYONHAND , REORDERLVL , SELLPRICE ,COSTPRICE )VALUES('P07865','jeans',5,'Piece',100,20,750,500);
INSERT INTO PRODUCT_MASTER_1(PRODUCTNO , DESCRIPTION , PROFITPERCENT , UNIT_MEASURE, QTYONHAND , REORDERLVL , SELLPRICE ,COSTPRICE )VALUES('P07868','trousers',2,'Piece',150,50,850,550);
INSERT INTO PRODUCT_MASTER_1(PRODUCTNO , DESCRIPTION , PROFITPERCENT , UNIT_MEASURE, QTYONHAND , REORDERLVL , SELLPRICE ,COSTPRICE )VALUES('P07885','pull overs',2.5,'Piece',80,30,700,450);
INSERT INTO PRODUCT_MASTER_1(PRODUCTNO , DESCRIPTION , PROFITPERCENT , UNIT_MEASURE, QTYONHAND , REORDERLVL , SELLPRICE ,COSTPRICE )VALUES('P07965','denim jeans',4,'Piece',100,40,350,250);
INSERT INTO PRODUCT_MASTER_1(PRODUCTNO , DESCRIPTION , PROFITPERCENT , UNIT_MEASURE, QTYONHAND , REORDERLVL , SELLPRICE ,COSTPRICE )VALUES('P07975','lycra tops',5,'Piece',70,30,300,175);
INSERT INTO PRODUCT_MASTER_1(PRODUCTNO , DESCRIPTION , PROFITPERCENT , UNIT_MEASURE, QTYONHAND , REORDERLVL , SELLPRICE ,COSTPRICE )VALUES('P08865','skirts',5,'Piece',75,30,450,300);

INSERT INTO SALESMAN_MASTER_1( SALESMANNO ,SALESMAN_NAME ,ADDRESS1 ,ADDRESS2 ,CITY ,PINCODE ,STATE,SALAMT,TGTTOGET,YTDSALES,REMARKS)VALUES('S00001','Aman','A/14','Worli','Mumbai',400002,'Maharashtra',1000,300,150,'never argues with anyone');
INSERT INTO SALESMAN_MASTER_1( SALESMANNO ,SALESMAN_NAME ,ADDRESS1 ,ADDRESS2 ,CITY,PINCODE,STATE,SALAMT,TGTTOGET,YTDSALES,REMARKS)VALUES('S00002','Omkar','65','Nariman','Mumbai',400001,'Maharashtra',2000,250,170,'Chances of mistakes is less');
INSERT INTO SALESMAN_MASTER_1( SALESMANNO ,SALESMAN_NAME ,ADDRESS1 ,ADDRESS2 ,CITY ,PINCODE ,STATE,SALAMT,TGTTOGET,YTDSALES,REMARKS)VALUES('S00003','Raj','P-7','Bandra','Mumbai',400032,'Maharashtra',3000,450,354,'Hard worker');
INSERT INTO SALESMAN_MASTER_1( SALESMANNO ,SALESMAN_NAME ,ADDRESS1 ,ADDRESS2 ,CITY ,PINCODE ,STATE,SALAMT,TGTTOGET,YTDSALES,REMARKS)VALUES('S00004','Ashish','A/5','Juhu','Mumbai',400044,'Maharashtra',4000,350,250,'passinate about the work');

CREATE TABLE AUTHOR (Author_ID varchar(5) primary key,
last_name varchar(15) NOT NULL,
first_name varchar(15) NOT NULL,
Email varchar(40) ,
City varchar(15),
country varchar(15));

select * from AUTHOR;

INSERT INTO AUTHOR(Author_ID,last_name,first_name,Email,City,country)VALUES('AOOOY','Mishra','Raj','r@gmail.com','Mohali','India');
INSERT INTO AUTHOR(Author_ID,last_name,first_name,Email,City,country)VALUES('AOOOU','Blake','Jennefer','jb@gmail.com','New york','America');
INSERT INTO AUTHOR(Author_ID,last_name,first_name,Email,City,country)VALUES('AOOON','Bond','James','j@gmail.com','London','United kingdom');
INSERT INTO AUTHOR(Author_ID,last_name,first_name,Email,City,country)VALUES('AOOOB','Kapoor','Amit','a@gmail.com','Delhi','India');


Create table BOOK (BOOK_ID varchar(5) CHECK (BOOK_ID LIKE 'B%')Primary key,
BOOK_TITLE varchar(15) NOT NULL,
COPIES Integer check(COPIES >2));

select * from BOOK;

INSERT INTO BOOK(BOOK_ID,BOOK_TITLE,COPIES)VALUES('BOOO1','BIRDS TALES',20);
INSERT INTO BOOK(BOOK_ID,BOOK_TITLE,COPIES)VALUES('BOOO2','ADBMS',15);
INSERT INTO BOOK(BOOK_ID,BOOK_TITLE,COPIES)VALUES('BOOO3','SPIDERMAN',5);
INSERT INTO BOOK(BOOK_ID,BOOK_TITLE,COPIES)VALUES('BOOO4','GOOSEBUMBS',10);


CREATE TABLE AUTHOR_LIST(
AUTHOR_ID VARCHAR(5),
BOOK_ID VARCHAR(5),
ROLE VARCHAR(15),
PRIMARY KEY(AUTHOR_ID,BOOK_ID),
FOREIGN KEY(AUTHOR_ID) REFERENCES AUTHOR(AUTHOR_ID));

ALTER TABLE AUTHOR_LIST
ADD(PUBLISHER VARCHAR(30));

SELECT * FROM AUTHOR_LIST;

CREATE TABLE BOOK_LIST(BOOK_ID varchar(5) CHECK (BOOK_ID LIKE 'B%')Primary key,
BOOK_NAME VARCHAR(15) NOT NULL );

select * from BOOK_LIST;

INSERT INTO BOOK_LIST(BOOK_ID,BOOK_NAME)VALUES('BOOO6','ADBMS');
INSERT INTO BOOK_LIST(BOOK_ID,BOOK_NAME)VALUES('BOOO8','AUTOMATA');
INSERT INTO BOOK_LIST(BOOK_ID,BOOK_NAME)VALUES('BOOO9','DATA MINING');
INSERT INTO BOOK_LIST(BOOK_ID,BOOK_NAME)VALUES('BOOO4','PYTHON');